spring:

---
spring:
  profiles: default
  cloud:
    stream:
      bindings:
        user-updates-publish:
          destination: user-updates.send
          content-type: application/json
        user-updates-subscribe:
          destination: user-updates.send
          content-type: application/json
---
spring:
  profiles: test
  cloud:
    config:
      enabled: false
